service: async-url-processor

provider:
  name: aws
  runtime: python3.7

plugins:
  - serverless-python-requirements

functions:
  get_url:
    handler: get_url.handler
    name: get_url
    events:
      - http:
          path: api/url
          method: get
          cors: true


package:
  exclude:
    - venv/** # virtualenv