service: async-url-processor

provider:
  name: aws
  runtime: python3.7
  memorySize: 512
  timeout: 10
  environment:
    WebPageContentsBucket: !Ref WebPageBucket
    DynamoTableName: !Ref UrlDynamoDbTable
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:*
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - Ref: WebPageBucket
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - Ref: WebPageBucket
            - "/*"
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/UrlTable"

plugins:
  - serverless-python-requirements

functions:
  get_url:
    handler: get_url.handler
    name: get_url
    events:
      - http:
          path: api/url
          method: get
          cors: true





resources:
  Resources:
    WebPageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: webpagecontents
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000
    UrlDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: UrlTable

# Print out the name of the bucket that is created
Outputs:
  WebPageBucket:
    Value:
      Ref: WebPageBucket


package:
  exclude:
    - venv/** # virtualenv
    - node_modules/**
    - .idea/**
    - README.md
    - package.json
    - package-lock.json
    - requirements.txt